project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_machinelearningfundamentals.qmd
          - text: "02 Supervised ML"
            file: content/01_journal/02_supervised_ml.qmd
          - text: "03 Automated Machine Learning with H2O"
            file: content/01_journal/03_automated_machine_learning_with_h2o.qmd
          - text: "04 Performance Measures"
            file: content/01_journal/04_performance_measures.qmd
          - text: "05 LIME"
            file: content/01_journal/05_lime.qmd
          - text: "06 Deep Learning"
            file: content/01_journal/06_deep_learning.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto
